import LandingNavbar from "@/components/landing/LandingNavbar";
import FooterSection from "@/components/landing/FooterSection";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-slate-900">
      <LandingNavbar />
      <main className="container mx-auto px-6 lg:px-8 pt-40 pb-20 max-w-4xl">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">
          Terms and Conditions
        </h1>
        <p className="text-slate-500 mb-12">Last updated: April 21, 2026</p>

        <div className="prose prose-slate max-w-none space-y-8 text-slate-600 leading-relaxed">
          <section>
            <p>
              These Terms and Conditions ("<strong>Terms</strong>") form a
              binding agreement between you ("<strong>you</strong>",
              "<strong>Customer</strong>", "<strong>Clinic</strong>") and
              Sitha Health Technologies Pvt. Ltd., a company incorporated in
              India with registered office at HSR Layout, Bangalore, Karnataka
              560102 ("<strong>Sitha</strong>", "we", "our", "us"), and govern
              your access to and use of Sitha-ai (the "<strong>Service</strong>"),
              available at sitha.ai, app.sitha.ai and any associated APIs,
              WhatsApp bots or mobile applications.
            </p>
            <p className="mt-3">
              By creating an account, connecting an Instagram or WhatsApp
              business account, or paying a subscription fee, you represent
              that you have read, understood and agree to be bound by these
              Terms, the <a href="/privacy" className="text-brand-cyan font-bold hover:underline">Privacy Policy</a>, the <a href="/refund" className="text-brand-cyan font-bold hover:underline">Refund Policy</a>, and our Acceptable Use Policy (Section 6).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              1. Definitions
            </h2>
            <ul className="list-disc pl-6 space-y-1.5">
              <li><strong>"Customer Content"</strong> means any data you upload — photos, captions, contact lists, brand assets, clinic and doctor information.</li>
              <li><strong>"AI Output"</strong> means text, images and carousels generated by the Service from your inputs.</li>
              <li><strong>"Plan"</strong> means a subscription tier (Starter, Growth, Scale or a custom plan) defining Service limits and features.</li>
              <li><strong>"Integration"</strong> means a third-party service (Meta/Instagram/WhatsApp, Razorpay, Google) that you authorize us to connect to on your behalf.</li>
              <li><strong>"Effective Date"</strong> means the date you first accept these Terms.</li>
              <li><strong>"Order"</strong> means the subscription selected at checkout plus any custom quote accepted in writing.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              2. Eligibility & Accounts
            </h2>
            <p className="mb-3">
              You must be at least 18 years old, possess legal capacity to
              contract, and have authority to bind the clinic or legal entity
              you register on behalf of. If you are a doctor, you warrant that
              you hold a valid registration with the relevant State Medical
              Council, National Medical Commission (NMC), or equivalent
              regulator.
            </p>
            <p>
              You are responsible for safeguarding credentials, enabling 2FA
              where offered, restricting staff access appropriately, and
              keeping contact details current. Notify security@sitha.ai
              immediately of any unauthorized account access.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              3. Description of the Service
            </h2>
            <p>Sitha-ai provides:</p>
            <ul className="list-disc pl-6 space-y-1.5 mt-3">
              <li>
                AI-powered generation of Instagram carousels, captions and
                short-form video suitable for dental, medical, aesthetic,
                wellness and allied-health clinics.
              </li>
              <li>
                Automated scheduling and publishing to connected Instagram and
                Facebook Business accounts via the official Meta Graph API.
              </li>
              <li>
                A WhatsApp-based approval workflow via the WhatsApp Business
                Cloud API.
              </li>
              <li>
                Bulk WhatsApp patient-outreach campaigns using Meta-approved
                message templates with delivery and engagement tracking.
              </li>
              <li>
                A Vision-AI pipeline that enhances and composes clinical
                photographs into on-brand carousel posts.
              </li>
              <li>
                Multi-clinic and multi-doctor persona management, daily
                auto-cron posting, and analytics dashboards.
              </li>
            </ul>
            <p className="mt-3">
              Feature availability, message quotas and API limits are
              determined by your Plan (see the <a href="/pricing" className="text-brand-cyan font-bold hover:underline">Pricing page</a>).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              4. Customer Content & Licence Grant
            </h2>
            <p className="mb-3">
              You retain all right, title, and interest in Customer Content.
              You grant Sitha a limited, non-exclusive, royalty-free,
              worldwide licence during the Term to:
            </p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Host, cache, store, back-up, reproduce, modify and display Customer Content solely to operate the Service for you.</li>
              <li>Transmit relevant Customer Content to authorized sub-processors (Meta APIs, Google Gemini, etc.) to generate and publish posts.</li>
              <li>Generate AI Output derived from Customer Content at your direction.</li>
            </ul>
            <p className="mt-3">
              This licence ends when you delete the content or close your
              account, subject to the retention periods in the Privacy Policy.
              <br />
              <strong>
                You warrant that you hold all necessary rights, consents, model
                releases, patient consents, and third-party licences to upload
                and publish Customer Content. You warrant that AI Output will
                be reviewed and approved by a qualified professional before
                publication.
              </strong>
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              5. AI Output — Ownership, Accuracy & Medical Responsibility
            </h2>
            <p className="mb-3">
              <strong>Ownership.</strong> Subject to your payment of all fees
              and compliance with these Terms, Sitha assigns to you all rights
              it holds in AI Output generated specifically for your account.
              You may use AI Output for any lawful purpose, including
              publication, print, or further derivative work.
            </p>
            <p className="mb-3">
              <strong>Accuracy.</strong> AI systems can produce inaccurate,
              biased or misleading content. The Service is a drafting tool, not
              a medical or legal authority. You are solely responsible for
              reviewing every piece of AI Output for:
            </p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Clinical accuracy and adherence to evidence-based guidelines.</li>
              <li>Compliance with the Drugs & Magic Remedies (Objectionable Advertisements) Act, 1954 and the ASCI Code.</li>
              <li>Accurate representation of doctor credentials and qualifications.</li>
              <li>Absence of prohibited claims (cure, guarantee, testimonials that violate MCI regulations).</li>
              <li>Appropriateness of any before/after imagery in your jurisdiction.</li>
            </ul>
            <p className="mt-3">
              <strong>
                Sitha does not provide medical, legal, or regulatory advice.
                Publication is always subject to your explicit approval.
              </strong>
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              6. Acceptable Use Policy
            </h2>
            <p className="mb-3">You agree not to, and not to permit any user to:</p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Use the Service to generate, publish, or distribute content that is unlawful, defamatory, hateful, obscene, or that violates any person's privacy or IP rights.</li>
              <li>Advertise prohibited treatments or make claims forbidden under the Drugs & Magic Remedies Act, the DCI Code of Ethics, the MCI/NMC Code of Ethics, or ASCI guidelines.</li>
              <li>Upload patient photographs without written informed consent from each depicted patient.</li>
              <li>Send bulk WhatsApp messages to contacts who have not opted-in, or ignore opt-out/STOP signals. You must comply with Meta's WhatsApp Business Messaging Policy and local telecom regulations (e.g. TRAI).</li>
              <li>Send promotional content outside the Meta-approved template categories permitted under your clinic's WABA.</li>
              <li>Attempt to reverse-engineer, scrape, decompile, benchmark, or clone the Service, its prompts, templates, or AI rendering engines.</li>
              <li>Circumvent plan limits, quotas, rate-limits, or authentication mechanisms.</li>
              <li>Resell, sub-license, or operate a service-bureau for third parties on the Service without a written reseller agreement.</li>
              <li>Use the Service to compete with Sitha, train machine-learning models, or benchmark against competing products.</li>
              <li>Introduce malware, perform load-testing without permission, or disrupt the Service's infrastructure.</li>
              <li>Impersonate another clinic, doctor, or Sitha itself.</li>
            </ul>
            <p className="mt-3">
              Violations may result in immediate suspension or termination
              without refund. Serious or repeat violations may be reported to
              law-enforcement or regulators (e.g. Meta policy violations
              reported to Meta Trust & Safety).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              7. Subscription Plans, Fees & Taxes
            </h2>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Plans are billed in advance (monthly or annually) in INR via Razorpay. Current pricing is on the <a href="/pricing" className="text-brand-cyan font-bold hover:underline">Pricing page</a>.</li>
              <li>Plans auto-renew at the end of each billing cycle unless cancelled at least 24 hours before renewal.</li>
              <li>Prices are exclusive of GST and other applicable taxes; you are liable for such taxes. We issue a GST-compliant tax invoice for every charge.</li>
              <li>We may revise published prices with 30 days' prior written notice; changes apply from your next renewal.</li>
              <li><strong>Usage-based overage:</strong> If you exceed your Plan's monthly WhatsApp broadcast quota or AI-post quota, overage is charged at the rates displayed in your dashboard. We will warn you at 80% and 100% of quota.</li>
              <li>Unpaid invoices older than 14 days may result in suspension of the Service; data is preserved for 30 days after suspension.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              8. Refunds, Cancellation & Free Trials
            </h2>
            <p>
              Refunds and cancellations are governed by the <a href="/refund" className="text-brand-cyan font-bold hover:underline">Refund & Cancellation Policy</a>. Free-trial and Growth-Pilot terms, including auto-conversion to paid, are presented at checkout and expressly accepted by you at that time.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              9. Third-Party Platforms & Integrations
            </h2>
            <p className="mb-3">
              The Service depends on third-party APIs (Meta Graph, WhatsApp
              Cloud, Google, Razorpay). Your use of those platforms is also
              governed by their own terms:
            </p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Meta Platform Terms, Instagram Terms of Use, WhatsApp Business Messaging Policy.</li>
              <li>Google API Services User Data Policy.</li>
              <li>Razorpay Merchant Terms of Service.</li>
            </ul>
            <p className="mt-3">
              Sitha is not liable for any third-party outage, rate-limit,
              policy change, account suspension, or fee charged by those
              platforms. You grant Sitha permission to act on your behalf on
              these platforms to the extent required to deliver the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              10. Data Processing & Confidentiality
            </h2>
            <p>
              When Sitha processes personal data on your behalf (e.g. patient
              contact lists, patient photographs), Sitha acts as a Data
              Processor and you as the Data Fiduciary/Controller. The <a href="/privacy" className="text-brand-cyan font-bold hover:underline">Privacy Policy</a> — together with our Data Processing Addendum (available on request) — forms part of these Terms and describes the processing, sub-processors, security measures and breach-notification commitments.
            </p>
            <p className="mt-3">
              Each party shall protect the other's confidential information
              with no less than a reasonable degree of care and use it solely
              to perform these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              11. Intellectual Property
            </h2>
            <p>
              Sitha, the Sitha-ai mark, our platform, source code, design
              system, templates (doctor, educational, engagement, promo, trust
              and any future templates), Clinical Guardrail prompt library,
              rendering engine, and documentation are the exclusive property
              of Sitha and protected under applicable laws. No licence is
              granted under these Terms other than the limited right to use
              the Service during a valid subscription.
            </p>
            <p className="mt-3">
              Feedback and suggestions you provide may be used by Sitha
              without restriction or obligation, provided we do not identify
              you as the source.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              12. Service Availability & Support
            </h2>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>We target 99.5% monthly uptime for the application and publishing pipeline; scheduled maintenance is notified in advance.</li>
              <li>Third-party outages (e.g. Meta API disruptions) are excluded from uptime calculations.</li>
              <li>Support SLAs vary by Plan (email 48h for Starter; WhatsApp 4h for Growth; 24/7 dedicated for Scale).</li>
              <li>Scale customers may request an Enterprise SLA with service credits via an Order form.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              13. Suspension & Termination
            </h2>
            <p className="mb-3">
              Sitha may suspend or terminate your account immediately, with or
              without notice, for:
            </p>
            <ul className="list-disc pl-6 space-y-1.5">
              <li>Material breach of these Terms or the Acceptable Use Policy.</li>
              <li>Non-payment of fees after reasonable notice.</li>
              <li>Activity that endangers the Service, other clinics, patients, or third-party platforms.</li>
              <li>A valid legal or regulatory demand, including Meta policy-enforcement notices.</li>
            </ul>
            <p className="mt-3">
              You may cancel at any time from your dashboard. Upon termination
              your access ceases at the end of the current billing period and
              your data is retained/deleted per the Privacy Policy. Sections
              1, 4 (rights in content), 5 (AI liability), 10, 11, 14–18 survive
              termination.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              14. Disclaimer of Warranties
            </h2>
            <p>
              The Service and AI Output are provided "<strong>as is</strong>" and
              "<strong>as available</strong>". To the maximum extent permitted
              by law, Sitha disclaims all warranties, express, implied,
              statutory, or otherwise, including warranties of merchantability,
              fitness for a particular purpose, non-infringement, accuracy, or
              error-free/uninterrupted operation. Sitha makes no warranty
              regarding the results achievable from using the Service (growth,
              engagement, revenue).
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              15. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, Sitha's aggregate
              liability under or in connection with these Terms — in contract,
              tort (including negligence), statute, or otherwise — shall not
              exceed the fees paid by you to Sitha in the 12 months preceding
              the event giving rise to the claim. In no event shall Sitha be
              liable for any indirect, incidental, special, consequential,
              exemplary, or punitive damages, including lost profits, lost
              data, loss of goodwill, regulatory fines, or patient
              dissatisfaction, even if advised of the possibility.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              16. Indemnification
            </h2>
            <p>
              You will defend, indemnify and hold Sitha, its officers and
              employees harmless from and against any third-party claim,
              proceeding, loss, damage, fine or expense (including reasonable
              legal fees) arising from: (a) Customer Content you uploaded; (b)
              AI Output you approved and published; (c) your breach of these
              Terms or Acceptable Use Policy; (d) your violation of any
              applicable law, medical-council code, or third-party platform
              policy.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              17. Force Majeure
            </h2>
            <p>
              Neither party shall be liable for failure to perform caused by
              events beyond its reasonable control, including acts of God,
              war, terrorism, civil unrest, pandemics, government action,
              internet outages, or third-party API failures, provided the
              affected party gives prompt notice and uses reasonable efforts
              to mitigate.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              18. Governing Law, Jurisdiction & Dispute Resolution
            </h2>
            <p>
              These Terms are governed by the laws of India, without regard to
              conflict-of-laws principles. The parties submit to the exclusive
              jurisdiction of the courts of Bangalore, Karnataka. Prior to
              filing suit, the parties will attempt to resolve any dispute
              through good-faith negotiation for 30 days, escalating to
              mediation under the Indian Mediation Act, 2023 if unresolved.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              19. Notices
            </h2>
            <p>
              Notices to you are given via email to your registered address or
              via in-app notification, and are deemed received on the day sent.
              Notices to Sitha must be sent to{" "}
              <a href="mailto:legal@sitha.ai" className="text-brand-cyan font-bold hover:underline">legal@sitha.ai</a>{" "}
              with a copy to our registered office, and are deemed received
              within 3 business days.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              20. Assignment
            </h2>
            <p>
              You may not assign these Terms without Sitha's prior written
              consent. Sitha may assign these Terms to an affiliate, successor
              in interest, or acquirer in a merger, acquisition or sale of
              substantially all assets, with notice to you.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              21. Changes to these Terms
            </h2>
            <p>
              We may update these Terms from time to time. Material changes
              will be notified at least 15 days in advance via email or in-app
              notice. If you do not accept the changes, you may terminate by
              cancelling before the effective date; continued use after that
              date constitutes acceptance.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              22. Miscellaneous
            </h2>
            <ul className="list-disc pl-6 space-y-1.5">
              <li><strong>Entire agreement:</strong> these Terms, together with the Privacy Policy, Refund Policy, DPA and any Order, constitute the entire agreement and supersede all prior understandings.</li>
              <li><strong>Severability:</strong> if any provision is held invalid, the remaining provisions remain in effect.</li>
              <li><strong>No waiver:</strong> a failure to enforce any right is not a waiver of that right.</li>
              <li><strong>No agency:</strong> nothing creates a partnership, joint venture or employment relationship between the parties.</li>
              <li><strong>Language:</strong> English is the controlling language. Translations are provided for convenience only.</li>
              <li><strong>Export & sanctions:</strong> you warrant you are not located in a sanctioned jurisdiction and will not use the Service in breach of sanctions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-slate-900 mb-4">
              23. Contact
            </h2>
            <div className="mt-4 p-6 rounded-2xl bg-slate-50 border border-slate-100 not-prose">
              <p className="font-bold text-slate-900">Sitha Health Technologies Pvt. Ltd.</p>
              <p className="text-slate-600 mt-1">
                HSR Layout, Bangalore, Karnataka 560102, India<br />
                Legal: <a href="mailto:legal@sitha.ai" className="text-brand-cyan font-bold hover:underline">legal@sitha.ai</a><br />
                Support: <a href="mailto:support@sitha.ai" className="text-brand-cyan font-bold hover:underline">support@sitha.ai</a><br />
                Billing: <a href="mailto:billing@sitha.ai" className="text-brand-cyan font-bold hover:underline">billing@sitha.ai</a>
              </p>
            </div>
          </section>
        </div>
      </main>
      <FooterSection />
    </div>
  );
}
